### ISSUE TITLE
GDX-SETUP-UI install issue

### ISSUE THREAD

**Issue by sharmavin** [octocat/Spoon-Knife#1740]
I am just starting and setting up environment.  I want to install GDX-SETUP-UI by following the steps at https://code.google.com/p/libgdx/wiki/ProjectSetupNew.  I get following error when running the command java -jar gdx-setup-ui.jar.  What am i doing wrong?  I am stuck here, please help.

---

Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: new c
hild is null
        at javax.swing.tree.DefaultMutableTreeNode.insert(Unknown Source)
        at javax.swing.tree.DefaultMutableTreeNode.add(Unknown Source)
        at aurelienribon.gdxsetupui.ui.panels.PreviewPanel$ResultTree.update(Unknown Source)
        at aurelienribon.gdxsetupui.ui.panels.PreviewPanel$ResultTree.<init>(Unknown Source)
        at aurelienribon.gdxsetupui.ui.panels.PreviewPanel.<init>(Unknown Source
)
        at aurelienribon.gdxsetupui.ui.MainPanel.<init>(Unknown Source)
        at aurelienribon.gdxsetupui.ui.Main$1.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$200(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

---

**Comment by sharmavin** [comment]
Help please
